title: Fabio's Website
description: Quelli che hanno una spada e sanno come usarla ma decidono di tenerla inguainata erediteranno il mondo
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]


collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  
remote_theme: pages-themes/minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme